### ISSUE TITLE
首页搜索栏可实现搜索引擎的接入吗

### ISSUE THREAD

**Issue by tocor163** [Mereithhh/van-nav#10]
你好，作者大大。
这个导航栏的羡慕，我一直在使用，当然你的博客，番茄钟，都非常棒，我都在使用。
这里提个小意见，导航栏 的搜索框可以接入搜索引擎吗，像bing 百度 Google，等等。
这样 van-nav 就可以直接作为浏览器的主页来使用了。
我也尝试着自己改，可我太菜了，无能为力。 
感谢您发布的这么多的优秀项目。

**Comment by DemoJ** [comment]
我第一想法也是有搜索引擎就完美了，正好作为主页

**Comment by Mereithhh** [comment]
安排！

**Comment by Mereithhh** [comment]
安排上了！等发版就有了。

**Comment by tocor163** [comment]
太酷啦！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月27日 19:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Mereithhh/van-nav] 首页搜索栏可实现搜索引擎的接入吗 (Issue #10) |

安排上了！等发版就有了。

**Comment by Mereithhh** [comment]
<img width="1009" alt="image" src="https://github.com/Mereithhh/van-nav/assets/22872368/69fd5f25-d67b-4b75-9758-c1491369011d">
你回复的很快，现在是这样的。还有啥建议吗？

**Comment by Mereithhh** [comment]
我打算在搜索后，给前9个卡片增加一个数字快捷键显示在右上角，这样除了按回车。使用数字按键也能快速导航了哈哈哈

**Comment by tocor163** [comment]
没有啦，已经很棒了，我一直在使用！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月27日 19:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Mereithhh/van-nav] 首页搜索栏可实现搜索引擎的接入吗 (Issue #10) |

你回复的很快，现在是这样的。还有啥建议吗？

**Comment by tocor163** [comment]
可以，很期待新版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月27日 19:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Mereithhh/van-nav] 首页搜索栏可实现搜索引擎的接入吗 (Issue #10) |

我打算在搜索后，给前9个卡片增加一个数字快捷键显示在右上角，这样除了按回车。使用数字按键也能快速导航了哈哈哈
