### ISSUE TITLE
点网站链接不是打开新的标签页？

### ISSUE THREAD

**Issue by pizixi** [Mereithhh/van-nav#16]
看demo网站是正常的，我用最新的release window包 ，点网站链接 直接在当前标签页打开了网站，而没有新开标签页 是咋回事？

**Comment by pizixi** [comment]
使用http://localhost:6412/ 正常，但是使用 ip+端口访问不正常

**Comment by Mereithhh** [comment]
![image](https://github.com/Mereithhh/van-nav/assets/22872368/033efd1d-d84b-466f-9d51-0902d35cd49b)

**Comment by Mereithhh** [comment]
有这个卡片，点一下就切换了啊

**Comment by pizixi** [comment]
哦哦。懂了，一直没搞清楚这个是干嘛的，我说的ip+端口访问 的时候为啥是原地跳转，应该是这个页面我点了那个按钮，使用localhost访问的时候没有点那个按钮
