### ISSUE TITLE
希望可以增加一个设置，来控制每次打开导航页时默认显示的分类

### ISSUE THREAD

**Issue by akimoto72738** [Mereithhh/van-nav#23]
如题，目前来说打开导航页时默认显示全部分类，但我希望可以在每次打开导航页是，默认显示指定的分类

这个项目页面简洁美观，真的很不错。打算长期用

**Comment by Mereithhh** [comment]
上次啥分类，再打开就是啥

**Comment by akimoto72738** [comment]
是的后来我发现了，所以我马上close掉了
