### ISSUE TITLE
添加网站时，获取网站图标卡住

### ISSUE THREAD

**Issue by DingDangDog** [Mereithhh/van-nav#3]
可能由于网络或什么原因，获取网站图标很慢，导致添加网站卡住，是否可考虑将该步请求改为异步，使其获取图标不要影响添加网站

**Comment by Mereithhh** [comment]
网站图标指的是页面左上角的，还是浏览器标签页的？

**Comment by DingDangDog** [comment]
> 网站图标指的是页面左上角的，还是浏览器标签页的？

后台添加收藏网址时候，不填网站图标地址，点击确定时候会自动获取图标，这时候有有时会卡住了。

**Comment by Mereithhh** [comment]
噢噢噢噢，我傻了，这是 van-nav 项目。我这两天修一下

**Comment by Mereithhh** [comment]
改了，等我发版了，更新一下就好了

**Comment by Mereithhh** [comment]
正在发版，`v1.4.2` 之后，增加工具和获取工具都是异步的，不会卡住添加工具了，另外真心推荐用一下插件，很好用 --
