### ISSUE TITLE
希望首页“全部工具”栏目里的内容可以按组展示

### ISSUE THREAD

**Issue by jolly90s** [Mereithhh/van-nav#32]
组别就是设置好的分类，以便于能很快的定位到网站链接的位置

**Comment by Mereithhh** [comment]
上方就有标签，点击就能很快的切换，并且也可以拼音搜索。 这样做似乎没有意义？

还是你想按照组别排序？

**Comment by jolly90s** [comment]
> 上方就有标签，点击就能很快的切换，并且也可以拼音搜索。 这样做似乎没有意义？
> 
> 还是你想按照组别排序？

是的 现在这样就挺好 谢谢！
