### ISSUE TITLE
建议：增加环境变量HTTPS_PROXY支持

### ISSUE THREAD

**Issue by efwfe** [Mereithhh/van-nav#34]
方便的话，请增加一个代理的支持，谢谢。

**Comment by Mereithhh** [comment]
这个变量的作用是啥？可以具体解释下吗？

如果想用 https，直接用 nginx/caddy 反代就行了。

你想给直接内置的 http server  加上 ssl？

**Comment by efwfe** [comment]
之前使用的时候很多网站拿不到icon，但是想设置一个的，目前没有啥场景了忘了关闭
