### ISSUE TITLE
管理后台密码重置问题

### ISSUE THREAD

**Issue by Hraulein** [Mereithhh/van-nav#36]
有一个小问题, 假设密码更改后忘记了如何重置? 似乎密码是存储在 nav.db 里的?

**Comment by kiraster** [comment]
密码是明文存储在 nav.db 文件，可将该文件拷贝至本地主机，使用支持sqlite数据库的图形化管理软件打开查看。

**Comment by Mereithhh** [comment]
楼上回答的很好，我加个 FAQ 到文档里吧

**Comment by Tmerowr** [comment]
如果nav.db文件也丢失了呢？只能重新部署了吧··
