### ISSUE TITLE
是否可以考虑加入“热门”的自动分类？

### ISSUE THREAD

**Issue by Emotion04** [Mereithhh/van-nav#41]
能否实现？自动按照该网址在站点（全网）的点击次数排序形成的一个分类，表示这些站点最受人欢迎，在自己全权分类的情况下多了另外一种分类可能

**Comment by Mereithhh** [comment]
这个项目的定位，是个人使用的，轻量级，自托管的在线收藏家/导航站，所以不会考虑做这个功能。

另外很难找到一个确定的指标表示全网热度
