### ISSUE TITLE
能否增加API调用文档

### ISSUE THREAD

**Issue by cnaron** [Mereithhh/van-nav#45]
主要使用的浏览器是Safari，而且手机端也想能直接添加网站，所以希望知道API调用，这样就能用快捷方式收藏网站了。

**Comment by Mereithhh** [comment]
增加了 API 的文档，但是 github 好像不能直接渲染 openai 规范，明天我做个文档站

**Comment by Mereithhh** [comment]
https://van-nav-api.mereith.dev/
