### ISSUE TITLE
排序功能优化的设想

### ISSUE THREAD

**Issue by sharkbear212** [Mereithhh/van-nav#48]
各位开发者，good day，
vannav老用户 用了一年多了
128条链接放在上面，
极简风格，快速搜索，都很满意
唯一的痛点是排序，首先系统有个自动生成的序号功能，是不可更改的。
然后又有个自己可以填的排序
我想让某个排在前面，现在是某一批是0，某一批是1，某一批是2，
不怎么需要考虑排序的就都设置成99
**不然改一个排序就要手动改所有的排序，没有自动排序。**
想要一个前台管理员手动拖动排序（最简单 但不确定是否复杂和可实现）
如果不可实现，想要把自动生成的序号和排序这个功能优化一下
![image](https://github.com/user-attachments/assets/75e7c579-60c7-4c8b-8eda-19228b4825dd)

**Comment by sharkbear212** [comment]
或者后台手动拖动排序，就像是wordpress里加了Simple Custom Post Order插件后，你去拖动文章排序一样
提前谢过开发者，希望有时间考虑优化一下

**Comment by Mereithhh** [comment]
ok，我安排下

**Comment by sharkbear212** [comment]
谢谢 已打赏 感谢带来这么好用的导航

**Comment by Mereithhh** [comment]
今天重构了一下代码，现在清晰多了，明天有空就做完排序功能。

**Comment by Mereithhh** [comment]
<img width="369" alt="Google Chrome 2024-12-08 18 33 25" src="https://github.com/user-attachments/assets/9eaf2791-77f4-4ada-8b46-3fc2ae3e82c2">

加上了，在 `v1.11.0` 版本中实现，走完发版流程就可以用上了

感谢支持
