### ISSUE TITLE
分类名修改

### ISSUE THREAD

**Issue by Southyang** [Mereithhh/van-nav#5]
博主能不能加一个分类名修改的功能啊，现在想改名只能删除再添加

不加也行hh，不影响前台使用

**Comment by Mereithhh** [comment]
可以改。仔细看文档，或者或者研究一下后台。
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/22872368/218047000-3a50f149-c9dd-48be-a854-5576919d8688.png">

**Comment by Southyang** [comment]
这个是van_nav项目，博主项目太多了hh😂

**Comment by Mereithhh** [comment]
啊，不好意思。 -  -，这个功能我明天就加上，最近开始折腾这个项目了。 这周末会加上主题自动切换和这个功能的。

**Comment by Southyang** [comment]
好嘞，这个项目的想法真的好，作为一个汇总的站点，找工具方便多了！
