### ISSUE TITLE
docker更新后，数据库全部丢失

### ISSUE THREAD

**Issue by nageshuizeii** [Mereithhh/van-nav#50]

**Comment by Mereithhh** [comment]
你更新的是： [v1.11.2](https://hub.docker.com/layers/mereith/van-nav/v1.11.2/images/sha256-c42d5f646c140f86a3d1122e4a41ed69ae972de1daefe1f0d6d1088eda02ca98) 吗？

其实数据没丢，你更新到最新的版本，或者回退到之前的版本应该就好了

**Comment by Mereithhh** [comment]
中间有一个版本， sqlite 驱动有问题，读不出来数据了

**Comment by nageshuizeii** [comment]
![CleanShot 2024-12-14 at 22 50 17@2x](https://github.com/user-attachments/assets/0009d427-cc7a-484d-9166-a12f1a25cb50)
docker的latest标签，确认数据没有了，nav.db都没有看见

**Comment by Mereithhh** [comment]
你启动的时候，没有映射数据库文件吗？

```
-v /path/to/your/data:/app/data
```

数据在容器内的 `/app/data` 中。

**Comment by Mereithhh** [comment]
我这边每一个版本都有用 docker 更新，应该没丢过数据的
![image](https://github.com/user-attachments/assets/5c806e7c-5b87-4804-9be8-49bf059dd32f)

**Comment by nageshuizeii** [comment]
![CleanShot 2024-12-14 at 22 54 04@2x](https://github.com/user-attachments/assets/938e61e0-4143-477e-a58d-1a2c3dd7ab46)
我也一直用的docker更新呀，就这一次没有数据了……

**Comment by nageshuizeii** [comment]
还是说这个版本改映射了

**Comment by Mereithhh** [comment]
你映射配错了，数据以及都在容器内的 `/app/data` 中，你映射里写的 `/data`

**Comment by Mereithhh** [comment]
没改过数据位置啊，从来都是 /app/data 里

**Comment by Mereithhh** [comment]
可能是之前你没更新上？ 我很久没发版本了

**Comment by nageshuizeii** [comment]
之前一直都是/data用的好好的，你看我提的issue都好久了，这下只有全部重新添加了……

**Comment by Mereithhh** [comment]
> 之前一直都是/data用的好好的，你看我提的issue都好久了，这下只有全部重新添加了……

你最近更新，和之前的更新在操作上有啥区别吗？

我的 dockerfile 其实会给 `/app/data` 声明一个 Volume，你之前一直配错了映射，但是 docker 会给你创建一个匿名的 Volume 用来持久化数据。

<img width="428" alt="image" src="https://github.com/user-attachments/assets/c6331513-e0f8-4758-ae04-47b303d5fc37" />

很可能你这次更新把匿名卷给删掉了……

**Comment by nageshuizeii** [comment]
就是群晖的自动更新😭没有其他多余操作

**Comment by Mereithhh** [comment]
> 的 dockerfile 其实会给 `/app/data` 声明一个 Volume，你之前一直配错了映射，但是 docker 会给你创建一个匿名的 Volume 用来持久化

那你的群晖系统有更新吗？或者重启？

**Comment by Mereithhh** [comment]
很抱歉给你带来了不便，我也没有好办法能帮你快速恢复数据了。

**Comment by nageshuizeii** [comment]
没有任何多余操作哈😭匿名的 Volume，这个怎么看呢

**Comment by Mereithhh** [comment]
```shell
docker volume ls
```

**Comment by Mereithhh** [comment]
你可以看看里面的卷，可能会有你的数据？ 另外问问 ai，可以帮助你

**Comment by nageshuizeii** [comment]
顺便报一个issue，更新之后，添加新的书签，要点两次增加，第一次增加是上一次添加的书签，第二次增加才是全空白
![CleanShot 2024-12-14 at 23 07 25@2x](https://github.com/user-attachments/assets/a3826be9-c94f-4a22-8eda-08e5b80dc9cb)

**Comment by Mereithhh** [comment]
> > 顺便报一个issue，更新之后，添加新的书签，要点两次增加，第一次增加是上一次添加的书签，第二次增加才是全空白 ![CleanShot 2024-12-14 at 23 07 25@2x](https://private-user-images.githubusercontent.com/16527235/395790865-a3826be9-c94f-4a22-8eda-08e5b80dc9cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODkyMjAsIm5iZiI6MTczNDE4ODkyMCwicGF0aCI6Ii8xNjUyNzIzNS8zOTU3OTA4NjUtYTM4MjZiZTktYzk0Zi00YTIyLThlZGEtMDhlNWI4MGRjOWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE1MDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNjkzZjZlN2Q3OTc1OGQ3MDIzNWY4OWUxMjAzNjliOTUxODI3ZTEyZWY3ODMzNmJhYjU2NjI4YjU2OGVhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.---llRSR8TmtDzQQ94sOzL1rtO4w1X6Ly-l-3dF1kGs)
> 
> 收到，我看看

我试了下，这个是因为前端的表单状态没清空，当时没做成清空的是因为有时候我会想添加完第一个工具后，在第一个表单的基础上改改再添加第二个。 不过感觉确实迷惑，我在下个版本改成清空的。

**Comment by Mereithhh** [comment]
修好了，发个版 - -

**Comment by nageshuizeii** [comment]
老镜像更新完了已经手快删除了，匿名卷也找不回数据了😭谢谢更新，真的很好用

**Comment by Mereithhh** [comment]
> 老镜像更新完了已经手快删除了，匿名卷也找不回数据了😭谢谢更新，真的很好用

![image](https://github.com/user-attachments/assets/101b6986-61a3-4f11-97e5-fbb363f3afff)

感谢支持。  保险起见，以后可以关闭自动更新，手动更新前导出一份数据稳妥些，数据无价

![image](https://github.com/user-attachments/assets/c6368d68-5964-407f-93b8-c2cd1e053ca9)
