### ISSUE TITLE
/admin/api-token 页面不能刷新

### ISSUE THREAD

**Issue by SoftBunny** [Mereithhh/van-nav#51]
登录后台后可以从左侧导航打开 /admin/api-token 页面，但F5刷新会报404错误，van-nav-extension也无法正常读取分类。

**Comment by Mereithhh** [comment]
收到，我看看

**Comment by Mereithhh** [comment]
修好了，更新生效 `v1.11.4`

**Comment by SoftBunny** [comment]
谢谢~

> 修好了，更新生效 `v1.11.4`
