### ISSUE TITLE
修改网站信息设置无效

### ISSUE THREAD

**Issue by ListenWaves** [Mereithhh/van-nav#53]
作者您好，网站标题、隐藏管理员后台卡片、隐藏github按钮设置修改无效，仍为默认
![image](https://github.com/user-attachments/assets/43b29390-099f-40e6-93bf-f2f26cf4c479)
![image](https://github.com/user-attachments/assets/15099608-a373-4d7b-8023-0b5e6db46bb9)

**Comment by Mereithhh** [comment]
收到，我看看

**Comment by Tjx356** [comment]
同上一样啊

**Comment by Mereithhh** [comment]
已修复
