### ISSUE TITLE
项目启动之后404

### ISSUE THREAD

**Issue by 276397082** [Mereithhh/van-nav#8]
我下载了源码，在vscode里面用`go run all`运行之后，无法访问，控制台提示404，只有`http://localhost:6412/api`可以访问，我是想把主页右下角那两个黑色的按钮删掉，页面上已经改了，用go build打包之后访问，也是提示404，文档啥时候出呀

**Comment by Mereithhh** [comment]
打包错了，参考 dockerfile 里面的打包，你需要逐步构建前端，然后复制静态资源最后才能 go build

**Comment by Mereithhh** [comment]
项目是全栈项目，只跑后端是不行的，有空我完善一下开发指南吧。现在代码也很屎，得重构了。

**Comment by Mereithhh** [comment]
项目已经重构。
