### ISSUE TITLE
提交2个bug，详情如下。

### ISSUE THREAD

**Issue by lovezsh** [Mereithhh/van-nav#9]
bug1: 新增工具条目后，再点击添加，输入框会保留上次的内容，这个时候直接新增下一个工具后，会覆盖上一个工具。

目前办法是，新增完先点击别的页面，再点击新增页面。

---

bug2: 在后台刷新时会直接丢失页面，较为频繁

![image](https://github.com/Mereithhh/van-nav/assets/65840178/d214a38a-0a36-45e9-a3f8-02c83dee4d84)

**Comment by Mereithhh** [comment]
第一个问题我修一下，第二个问题我从来没遇到，也没听别人反馈过。 你可以换个浏览器或者网络环境试试，如果还是不行，检查一下你的部署链路，大概率不是 vanblog 本身的问题

**Comment by lovezsh** [comment]
> 第一个问题我修一下，第二个问题我从来没遇到，也没听别人反馈过。 你可以换个浏览器或者网络环境试试，如果还是不行，检查一下你的部署链路，大概率不是 vanblog 本身的问题

@Mereithhh 貌似是我反代的问题，感谢回复。

**Comment by Mereithhh** [comment]
第二个也是我的问题，两个我都修好了，等发版更新一下就好了。

**Comment by lovezsh** [comment]
@Mereithhh 谢谢 😍

**Comment by Mereithhh** [comment]
不客气 欢迎提出建议
